language: node_js
node_js:
  - 14

script:
  - '$(npm bin)/knapsack-pro-jest --runInBand'

env:
  global:
    - KNAPSACK_PRO_CI_NODE_TOTAL=10
    # allows to be able to retry failed tests on one of parallel job (CI node)
    - KNAPSACK_PRO_FIXED_QUEUE_SPLIT=true

  jobs:
    - KNAPSACK_PRO_CI_NODE_INDEX=0
    - KNAPSACK_PRO_CI_NODE_INDEX=1
    - KNAPSACK_PRO_CI_NODE_INDEX=2
    - KNAPSACK_PRO_CI_NODE_INDEX=3
    - KNAPSACK_PRO_CI_NODE_INDEX=4
    - KNAPSACK_PRO_CI_NODE_INDEX=5
    - KNAPSACK_PRO_CI_NODE_INDEX=6
    - KNAPSACK_PRO_CI_NODE_INDEX=7
    - KNAPSACK_PRO_CI_NODE_INDEX=8
    - KNAPSACK_PRO_CI_NODE_INDEX=9